- name: create /etc/pacman.d/hooks/ directory
  file:
    path: /etc/pacman.d/hooks/
    state: directory
    mode: '0755'

# https://wiki.archlinux.org/index.php/Systemd-boot#Automatic_update
- name: systemd-boot pacman hook
  copy: src=hooks/100-systemd-boot.hook dest=/etc/pacman.d/hooks/
