# https://wiki.archlinux.org/index.php/Secure_Boot#PreLoader
# https://aur.archlinux.org/cgit/aur.git/plain/PKGBUILD?h=preloader-signed

- name: "download {{ item.name }}"
  get_url:
    url: "https://blog.hansenpartnership.com/wp-uploads/2013/{{ item.name }}"
    checksum: "{{ item.checksum }}"
    dest: /boot/EFI/systemd/
    mode: '0644'
  loop:
    - { name: 'PreLoader.efi', checksum: 'sha512:c73583439ad989f5eb3a68753df56a06dc2f04b637415e3c515c74654651e0991a1d5f0ab84da4cd1d681d29a35271ff584a5b988b28ce1b810f94c0d0a57aff' }
    - { name: 'HashTool.efi', checksum: 'sha512:a51ce176c93417e53ec6d78c16afa5e8b9545e623d98d4fc55fc3762f33cd942ea1dce1211b2ed80703df08fe4fed84aff1fa86063c27b08413b3882019c4afd' }

- name: copy systemd-bootx64.efi
  copy: src=/boot/EFI/systemd/systemd-bootx64.efi dest=/boot/EFI/systemd/loader.efi
