- name: create /etc/sysctl.d/ directory
  file:
    path: /etc/sysctl.d/
    state: directory
    mode: '0755'

- name: sysctl config
  copy: src=sysctl.d/{{ item.src }} dest=/etc/sysctl.d/
  with_items:
    - { src: 'hardening.conf' }
    - { src: 'vm.conf' }
