- name: audio packages
  pacman:
    name:
      - pipewire
      - pipewire-alsa
      - pipewire-jack
      - pipewire-pulse
      - pavucontrol
    state: present
  become: yes

- name: players
  pacman:
    name:
      - quodlibet
      - gst-plugins-good
    state: present
  become: yes
