- name: "Is {{ name }} already installed"
  shell: pacman -Q | grep '^{{ name }} '
  register: installed
  ignore_errors: True

- block:
  - name: "{{ name }} dependencies"
    pacman:
      name: "{{ dependencies }}"
      state: present
    become: yes

  - name: "{{ name }} download"
    unarchive: src=https://aur.archlinux.org/cgit/aur.git/snapshot/{{ name }}.tar.gz dest=/tmp copy=no

  - name: "{{ name }} build"
    shell: chdir=/tmp/{{ name }} creates={{ name }}.pkg.tar makepkg -f --skippgpcheck && mv *.pkg.tar {{ name }}.pkg.tar

  - name: "{{ name }} install"
    shell: chdir=/tmp/{{ name }} pacman --noconfirm -U {{ name }}.pkg.tar
    become: yes

  when: installed is failed
