- name: "Is {{ pkg }} already installed"
  shell: pacman -Q | grep '^{{ pkg }} '
  register: installed
  ignore_errors: True

- block:
  - name: "{{ pkg }} dependencies"
    pacman:
      name: "{{ dependencies }}"
      state: present
    become: yes

  - name: "{{ pkg }} download"
    unarchive: src=https://aur.archlinux.org/cgit/aur.git/snapshot/{{ pkg }}.tar.gz dest=/tmp copy=no

  - name: "{{ pkg }} build"
    shell: chdir=/tmp/{{ pkg }} creates={{ pkg }}.pkg makepkg -f --skippgpcheck && mv *.pkg.* {{ pkg }}.pkg

  - name: "{{ pkg }} install"
    shell: chdir=/tmp/{{ pkg }} pacman --noconfirm -U {{ pkg }}.pkg
    become: yes

  when: installed is failed
