- name: install dnsmasq
  pacman:
    name:
      - dnsmasq
      - openresolv
    state: present
  become: yes

- name: load dnsmasq config files in /etc/dnsmasq.d
  lineinfile:
    path: /etc/dnsmasq.conf
    regexp: '^conf-dir=/etc/dnsmasq.d'
    line: conf-dir=/etc/dnsmasq.d
  become: yes

- name: create /etc/dnsmasq.d directory
  file:
    path: /etc/dnsmasq.d/
    state: directory
    mode: '0755'
  become: yes

- name: dnsmasq dns config
  copy: src=dnsmasq.d/dns.conf dest=/etc/dnsmasq.d/dns.conf
  become: yes

- name: disable systemd-resolved
  systemd:
    name: systemd-resolved.service
    state: stopped
    enabled: no
  become: yes

- name: enable dnsmasq
  systemd:
    name: dnsmasq.service
    state: started
    enabled: yes
  become: yes

- name: use dnsmasq dns
  lineinfile:
    path: /etc/resolvconf.conf
    regexp: '^name_servers='
    line: name_servers=127.0.0.1
  become: yes
