# these packages are from base-devel but it requires a user selection
- name: makepkg dependencies
  pacman:
    name:
      - autoconf
      - automake
      - binutils
      - fakeroot
      - gcc
      - make
      - pkg-config
    state: present
  become: yes
