- name: terminal packages (x11)
  pacman:
    name:
      - xterm
      - rxvt-unicode
      - urxvt-perls
      - x11-ssh-askpass
      - xclip
    state: present
  become: yes

- name: terminal packages (wayland)
  pacman:
    name:
      - foot
    state: present
  become: yes
