- name: video packages
  pacman:
    name:
      - xterm
      - xf86-video-vesa
      - xf86-video-ati
      - xf86-video-intel
      - xf86-video-nouveau
      - libva-vdpau-driver
      - mesa-vdpau
      - xorg-server
      - xorg-xinit
      - xorg-xrdb
      - mplayer
    state: present
  become: yes
