- name: video packages
  pacman:
    name:
      - mesa-vdpau
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - xorg-xrdb
      - xscreensaver
      - mpv
    state: present
  become: yes
