- name: video packages
  pacman:
    name:
      - xterm
      - xf86-video-vesa
      - xf86-video-intel
      - libva-vdpau-driver
      - mesa-vdpau
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - xorg-xrdb
      - xscreensaver
      - mpv
    state: present
  become: yes
