- name: video packages
  pacman:
    name:
      - mesa-vdpau
      - mpv
    state: present
  become: yes

- name: video packages (x11)
  pacman:
    name:
      - xorg-server
      - xorg-xinit
      - xorg-xrandr
      - xorg-xrdb
    state: present
  become: yes

- name: video packages (wayland)
  pacman:
    name:
      - kanshi
      - wlr-randr
    state: present
  become: yes
